# Generated by Django 2.0.5 on 2018-06-18 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20180619_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2018, 6, 19, 0, 22, 55, 885704)),
        ),
    ]
